-- 002_contractor.sql — One-time wipe+recreate migration per D-05/D-09.
--
-- PURPOSE: Adds the `contractor` column to `bid_items` by dropping and fully
-- recreating all four data tables with the updated schema.
--
-- NOTE: After this migration runs once, all four tables exist and stay populated
-- across API restarts (the run-once schema_migrations tracker prevents re-runs).
-- The user must re-upload their CSV after this migration to repopulate data.
--
-- This migration is applied EXACTLY ONCE by DatabaseService's sorted-glob runner
-- (gated by schema_migrations). It does NOT run on every restart.

-- ── Step 1: Drop all tables (vec_chunks first — virtual table with no dependents) ─
DROP TABLE IF EXISTS vec_chunks;
DROP TABLE IF EXISTS chunks;
DROP TABLE IF EXISTS bid_items;
DROP TABLE IF EXISTS documents;

-- ── Step 2: Recreate all four tables with updated schema ──────────────────────

-- chunks: unchanged from 001_init.sql
CREATE TABLE chunks (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  document_id TEXT    NOT NULL,
  content     TEXT    NOT NULL,
  metadata    TEXT,                          -- JSON blob: {page?, rowStart?, rowEnd?, itemCode?}
  created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- bid_items: now includes `contractor TEXT` as the final column (ENG-07)
CREATE TABLE bid_items (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  document_id TEXT    NOT NULL,
  item_code   TEXT,
  description TEXT,
  unit        TEXT,
  quantity    REAL,
  unit_price  REAL,
  total_price REAL,
  contractor  TEXT
);

-- documents: unchanged from 001_init.sql
CREATE TABLE documents (
  id         TEXT     PRIMARY KEY,          -- UUID v4 generated by IngestService
  filename   TEXT,
  mime_type  TEXT,
  parse_log  TEXT     NOT NULL,             -- JSON: ParseLog interface (D-09)
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- vec_chunks: unchanged from 001_init.sql; {{EMBEDDING_DIM}} substituted at runtime
CREATE VIRTUAL TABLE vec_chunks USING vec0(
  embedding float[{{EMBEDDING_DIM}}]
);
